services:
  - type: web
    name: wordpress-mcp
    plan: starter
    env: node
    region: oregon
    buildCommand: npm ci
    startCommand: ./start.sh
    healthCheckPath: /
    domains:
      - wordpress-mcp.onrender.com
    envVars:
      - key: NODE_VERSION
        value: 18.12.1
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WP_SITE_URL
        fromDatabase:
          name: wordpress_site_url
          property: connectionString
      - key: WP_USERNAME
        sync: false
      - key: WP_APP_PASSWORD
        sync: false
      - key: LOG_LEVEL
        value: info
      - key: HEADLESS
        value: "true"
      - key: MAX_API_CONNECTIONS
        value: 3
      - key: MAX_BROWSER_CONNECTIONS
        value: 1
      - key: REQUIRE_API_KEY
        value: "true"
      - key: RATE_LIMIT_WINDOW_MS
        value: 60000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 60
      - key: MCP_PROTOCOL_VERSION
        value: 2025-03-26

databases:
  - name: wordpress_site_url
    databaseName: wordpress_site_url
    user: wordpress_site_url_user 